# Generated by Django 3.2.6 on 2021-12-11 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 12, 11, 9, 28, 41, 236650, tzinfo=utc), upload_to='product_images/', verbose_name='Product image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Tovar alohida rasmlari')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Tovar rasmlari',
                'verbose_name_plural': 'Tovar rasmlari',
            },
        ),
    ]
