# Generated by Django 3.2.6 on 2022-01-04 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cardproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=datetime.datetime(2022, 1, 4, 8, 34, 6, 249397, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
